### ISSUE TITLE
error running the storybook server

### ISSUE THREAD

**Issue by nicopace** [LibreRouterOrg/soporteremoto-dashboard#2]
@germanferrero wanted to try the progress and this is what I got:

Can you help me sort it out?
```
nico@ingorian:~/tmp/librerouterorg/soporteremoto-dashboard/web-app$ nvm use v8.10.0
Now using node v8.10.0 (npm v5.6.0)
nico@ingorian:~/tmp/librerouterorg/soporteremoto-dashboard/web-app$ yarn run storybook
yarn run v1.16.0
error Command "storybook" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
nico@ingorian:~/tmp/librerouterorg/soporteremoto-dashboard/web-app$ ls
config-overrides.js  node_modules  package.json  public  README.md  src  yarn.lock
nico@ingorian:~/tmp/librerouterorg/soporteremoto-dashboard/web-app$ yarn run
yarn run v1.16.0
info Commands available from binary scripts: acorn, ansi-html, atob, autoprefixer, babylon, browserslist, build-storybook, css-blank-pseudo, css-has-pseudo, css-prefers-color-scheme, cssesc, detect, detect-port, errno, escodegen, esgenerate, eslint, esparse, esvalidate, handlebars, he, html-minifier, import-local-fixture, is-ci, jest, jest-runtime, js-yaml, jsesc, json5, loose-envify, marked, miller-rabin, mime, mkdirp, multicast-dns, parser, react-app-rewired, react-docgen, react-scripts, regexp-tree, regjsparser, rimraf, sane, semver, sha.js, shjs, sshpk-conv, sshpk-sign, sshpk-verify, start-storybook, storybook-server, svgo, terser, uglifyjs, uuid, watch, webpack, webpack-dev-server, which
info Project commands
   - build
      react-app-rewired build
   - eject
      react-scripts eject
   - start
      react-app-rewired start
   - test
      react-app-rewired test
question Which command would you like to run?: start-sorybook
error Command "start-sorybook" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
nico@ingorian:~/tmp/librerouterorg/soporteremoto-dashboard/web-app$ yarn run start-storybook
yarn run v1.16.0
$ /home/nico/tmp/librerouterorg/soporteremoto-dashboard/web-app/node_modules/.bin/start-storybook
info @storybook/react v5.1.9
info 
info => Loading presets
info => Loading presets

WARN Broken build, fix the error below.
WARN You may need to refresh the browser.

ERR! Error: => Create a storybook config file in "./.storybook/config.{ext}".
ERR!     at createPreviewEntry (/home/nico/tmp/librerouterorg/soporteremoto-dashboard/web-app/node_modules/@storybook/core/dist/server/preview/entries.js:21:11)
ERR!     at <anonymous>
ERR!     at process._tickCallback (internal/process/next_tick.js:188:7)
ERR!     at Function.Module.runMain (module.js:695:11)
ERR!     at startup (bootstrap_node.js:188:16)
ERR!     at bootstrap_node.js:609:3
ERR!  { Error: => Create a storybook config file in "./.storybook/config.{ext}".
ERR!     at createPreviewEntry (/home/nico/tmp/librerouterorg/soporteremoto-dashboard/web-app/node_modules/@storybook/core/dist/server/preview/entries.js:21:11)
ERR!     at <anonymous>
ERR!     at process._tickCallback (internal/process/next_tick.js:188:7)
ERR!     at Function.Module.runMain (module.js:695:11)
ERR!     at startup (bootstrap_node.js:188:16)
ERR!     at bootstrap_node.js:609:3
ERR!   stack: 'Error: => Create a storybook config file in "./.storybook/config.{ext}".\n    at createPreviewEntry (/home/nico/tmp/librerouterorg/soporteremoto-dashboard/web-app/node_modules/@storybook/core/dist/server/preview/entries.js:21:11)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)\n    at Function.Module.runMain (module.js:695:11)\n    at startup (bootstrap_node.js:188:16)\n    at bootstrap_node.js:609:3' }
Done in 7.44s.
nico@ingorian:~/tmp/librerouterorg/soporteremoto-dashboard/web-app$ yarn run storybook-server
yarn run v1.16.0
$ /home/nico/tmp/librerouterorg/soporteremoto-dashboard/web-app/node_modules/.bin/storybook-server
info @storybook/react v5.1.9
info 
info => Loading presets
info => Loading presets

WARN Broken build, fix the error below.
WARN You may need to refresh the browser.

ERR! Error: => Create a storybook config file in "./.storybook/config.{ext}".
ERR!     at createPreviewEntry (/home/nico/tmp/librerouterorg/soporteremoto-dashboard/web-app/node_modules/@storybook/core/dist/server/preview/entries.js:21:11)
ERR!     at <anonymous>
ERR!     at process._tickCallback (internal/process/next_tick.js:188:7)
ERR!     at Function.Module.runMain (module.js:695:11)
ERR!     at startup (bootstrap_node.js:188:16)
ERR!     at bootstrap_node.js:609:3
ERR!  { Error: => Create a storybook config file in "./.storybook/config.{ext}".
ERR!     at createPreviewEntry (/home/nico/tmp/librerouterorg/soporteremoto-dashboard/web-app/node_modules/@storybook/core/dist/server/preview/entries.js:21:11)
ERR!     at <anonymous>
ERR!     at process._tickCallback (internal/process/next_tick.js:188:7)
ERR!     at Function.Module.runMain (module.js:695:11)
ERR!     at startup (bootstrap_node.js:188:16)
ERR!     at bootstrap_node.js:609:3
ERR!   stack: 'Error: => Create a storybook config file in "./.storybook/config.{ext}".\n    at createPreviewEntry (/home/nico/tmp/librerouterorg/soporteremoto-dashboard/web-app/node_modules/@storybook/core/dist/server/preview/entries.js:21:11)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)\n    at Function.Module.runMain (module.js:695:11)\n    at startup (bootstrap_node.js:188:16)\n    at bootstrap_node.js:609:3' }
Done in 6.64s.
nico@ingorian:~/tmp/librerouterorg/soporteremoto-dashboard/web-app$ 
```

**Comment by germanferrero** [comment]
We tried to reproduce the error with:
yarn run storybook

at office, but it worked as expected :)
